"""First Migration

Revision ID: 74e24f4c9ce5
Revises: 
Create Date: 2019-08-22 20:43:32.338637

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from api_server.modules.plugin.models import STATUS


# revision identifiers, used by Alembic.
revision = '74e24f4c9ce5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'service',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('plugin_name', sa.String(length=250), nullable=False),
        sa.Column('plugin_command', sa.String(length=255), nullable=False),
        sa.Column('service_uuid', sa.String(length=64), nullable=False),
        sa.Column('is_server', sa.Boolean(), nullable=False),
        sa.Column('process_id', sa.String(length=64), nullable=True),
        sa.Column('access_url', sa.String(length=255), nullable=False),
        sa.Column('proxy_url', sa.String(length=255), nullable=True),
        sa.Column('workdir', sa.String(length=255), nullable=True),
        sa.Column('src_code_dir', sa.String(length=255), nullable=True),
        sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(STATUS), nullable=False),
        sa.Column('message', sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_service_uuid'), 'service', ['service_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_service_uuid'), table_name='service')
    op.drop_table('service')
    # ### end Alembic commands ###
