{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set url = data.get('url') %}
{% set description = data.get('description') %}

package:
  name: next_service_engine
  version: {{ version }}


source:
  - path: ../


build:
  include_recipe: True
  entry_points:
    - next_service_engine = api_server.server:run_server


requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - plotly
    - bokeh
    - Jinja2
    - Markdown
    - pyparsing
    - requests
    - multiqc>=1.7
    - sqlalchemy
    - docker-py
    - psutil

# test:
#   imports:
#     - next_service_engine

about:
  home: {{ url }}
  license: AGPL 3.0
  license_file: LICENSE.md
  license_family: GNU

  summary: {{ description }}
  description: {{ description }}
  doc_url: http://docs.3steps.cn
  dev_url: {{ url }}